layout_spectrum: 0.607023160206154
typography_spectrum: 0.5139443634543568
color:
  brandStrength: 0.34787937183864415
  lightness: 0.235201419563964
  saturation: 0.7332304089795798
  rhythmicContrast: 0.9371418240480125
  brandColors:
    - '#00261C'
    - '#044D29'
    - '#168039'
    - '#45BF55'
    - '#96ED89'
name: CFAMM
