layout_spectrum: 0.607023160206154
typography_spectrum: 0.5139443634543568
color:
  brandStrength: 0.34787937183864415
  lightness: 0.235201419563964
  saturation: 0.7332304089795798
  rhythmicContrast: 0.9371418240480125
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
name: CFAMM
